spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:halyk_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
    baseline-version: 0.0.0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true